### ISSUE TITLE
MetaPhlAn DB location

### ISSUE THREAD

**Issue by fbeghini** [waldronlab/curatedMetagenomicDataHighLoad#14]
https://github.com/waldronlab/curatedMetagenomicDataHighLoad/blob/master/docker/curatedMetagenomics/curatedMetagenomicData_pipeline.sh#L18

Are the MetaPhlAn database provided by mounting a volume or included directly in the Docker image?

**Comment by lwaldron** [comment]
I want them to be provided by mounting a volume - this whole script certainly needs to be updated.

**Comment by lwaldron** [comment]
But, what difference does it make for the curatedMetagenomicData_pipeline.sh script whether the databases are mounted or in the image?

**Comment by fbeghini** [comment]
No differences, I was wondering if `metaphlan --install latest` was needed to include in the Dockerfile

**Comment by lwaldron** [comment]
Ah I see - no I think the databases will be downloaded / mounted separately
to avoid bloating the Docker container but also avoid downloading with
every sample processed. But thanks for this command, I tested it and found
it downloads the databases from Dropbox which seems to be much faster than
the `humann3_databases` Harvard URLs. FYI @cmirzayi

**Comment by lwaldron** [comment]
@fbeghini I'm finding that the following takes forever (15 minutes and counting...) - is this related to using the correct MetaPhlAn DB?
```
export DB_PATH="${HOME}/biobakery.db"; docker run -it -e ncores=2 -v ${DB_PATH}/metaphlan:/usr/local/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan_databases -v ${DB_PATH}/humann:/usr/local/humann_databases waldronlab/curatedmetagenomics
root@d499ae27c16e:~# curatedMetagenomicData_pipeline.sh demosamplename SRR042612 DEMO
```

**Comment by fbeghini** [comment]
Was `docker top` showing that `bowtie2-build` was running?
