### ISSUE TITLE
update curatedMetagenomicData_pipeline.sh

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicDataHighLoad#15]
@fbeghini, could you help update [curatedMetagenomicData_pipeline.sh](https://github.com/waldronlab/curatedMetagenomicDataHighLoad/blob/master/docker/curatedMetagenomics/curatedMetagenomicData_pipeline.sh). I think it only needs a couple things:

- [x] call humann3 instead of humann2
- [x] use databases from default location, but include comments about what that location is and how to download them
- [x] accept the semicolon-delimited list of SRA run accession IDs, but provide these to `fastq-dump` space-separated
- [x] try calling `fasterq-dump` instead of `fastq-dump`?
- [x] check that it works with the `waldronlab/curatedmetagenomics` Docker image
- [x] add a non-default argument that causes using DEMO databases instead of full databases to be used

**Comment by lwaldron** [comment]
Thanks @fbeghini! And sorry, I just added one more item to the checklist: "add a non-default argument that causes DEMO databases to be used instead of full databases." This will make pipeline building and testing easier. But at least, I did some of the work on database location. I think the following works (ie I can see the directories in the Docker container, but haven't done any test runs), where `/nobackup/16tb_b/biobakery.db` is a host directory for databases:

```
docker run -it -v /nobackup/16tb_b/biobakery.db/metaphlan:/usr/local/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan_databases -v /nobackup/16tb_b/biobakery.db/humann:/usr/local/humann_databases waldronlab/curatedmetagenomics 6d584473b570
# Note: replace local build 6d584473b570 with waldronlab/curatedmetagenomics once the Dockerhub build is finished
```

Within the Docker container, the environment variables `$metaphlandb` and `$humanndb` give the database locations, and `curatedMetagenomicData_pipeline.sh` and `run_markers2.py` are in the $PATH:

```bash
root@06f80fce76e7:~# echo $metaphlandb
/usr/local/miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan_databases
root@06f80fce76e7:~# ls $metaphlandb
file_list.txt                     mpa_v296_CHOCOPhlAn_201901.2.bt2  mpa_v296_CHOCOPhlAn_201901.fna.bz2  mpa_v296_CHOCOPhlAn_201901.rev.1.bt2
mpa_latest                        mpa_v296_CHOCOPhlAn_201901.3.bt2  mpa_v296_CHOCOPhlAn_201901.md5      mpa_v296_CHOCOPhlAn_201901.rev.2.bt2
mpa_v296_CHOCOPhlAn_201901.1.bt2  mpa_v296_CHOCOPhlAn_201901.4.bt2  mpa_v296_CHOCOPhlAn_201901.pkl      mpa_v296_CHOCOPhlAn_201901.tar
root@06f80fce76e7:~# echo $humanndb
/usr/local/humann_databases
root@06f80fce76e7:~# ls $humanndb
chocophlan                          uniref                uniref90_DEMO_diamond_v201901.tar.gz  uniref90_demo_prots_v201901.dmnd
full_chocophlan.v296_201901.tar.gz  uniref90_201901.dmnd  uniref90_annotated_v201901.tar.gz
root@06f80fce76e7:~# which curatedMetagenomicData_pipeline.sh
/usr/local/bin/curatedMetagenomicData_pipeline.sh
root@06f80fce76e7:~# which run_markers2.py
/usr/local/bin/run_markers2.py
root@06f80fce76e7:~# 
```

**Comment by fbeghini** [comment]
>accept the semicolon-delimited list of SRA run accession IDs, but provide these to fastq-dump space-separated
`fasterq-dump` accepts only one SRA accession at the time, it seems to be faster than `ascp`

**Comment by lwaldron** [comment]
How about doing this:
```bash
#!/bin/bash

### usage: bash curatedMetagenomicData_pipeline.sh sample_name "SRRxxyxyxx;SRRyyxxyyx"

sample=$1
runs=$2

for run in $(echo $runs | sed "s/;/ /g")
do
    fasterq-dump "$run"
done
```

**Comment by fbeghini** [comment]
```
for run in ${runs//;/ }
do
	echo 'Dumping run '${run}
    fasterq-dump --threads ${ncores} --split-files ${run} --outdir ${sample}/reads/
    echo 'Finished downloading of run '${run}
done
```

This uses BASH string replacement

**Comment by lwaldron** [comment]
Excellent.

**Comment by fbeghini** [comment]
For running the DEMO, shall we use the `demo.fastq` provided with HUMAnN combined with the reduced databases? If we use a run from SRA, the result may be empty.

I was thinking to trigger the DEMO test when the run parameter is set to `DEMO`.

**Comment by lwaldron** [comment]
DEMO test sounds good - it would still use the arguments for fasterq-dump and naming, but the output would be the results of DEMO test no matter for any accession numbers.

**Comment by fbeghini** [comment]
I've tested the pipeline script with the DEMO example and it works. For reference, I've put the command on the top of the script
`bash curatedMetagenomicData_pipeline.sh DEMO SRR042612 DEMO`

**Comment by lwaldron** [comment]
This is great, @fbeghini ! Question - should we use subdirectories of the `$hnn_dir` you've defined to store humann chocophlan and uniref databases, instead of subdirectories of the `$humann_databases` directory I defined (`ENV humanndb=/usr/local/humann_databases`)?

https://github.com/waldronlab/curatedMetagenomicDataHighLoad/blob/072969a7a859032d622214e8a650f9b9805cfd41/docker/curatedMetagenomics/Dockerfile#L56

**Comment by fbeghini** [comment]
No, I'd keep the two things separated, the `$hnn_dir` (for now) is defined only for looking the DEMO file

**Comment by lwaldron** [comment]
I can confirm it's working for me too. Note that the script is in the PATH (`/usr/local/bin`), so you can just do for example:
```bash
curatedMetagenomicData_pipeline.sh demosample SRR042612 DEMO
```
