### ISSUE TITLE
Is setting $mdbn variable necessary?

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicDataHighLoad#19]
It will require hard-coded updates, and is only used by `run_markers2.py` for the flag `--metaphlan_db ${mdbn}`. Can `$mdbn` be automatically from the installed databases?

https://github.com/waldronlab/curatedMetagenomicDataHighLoad/blob/502f4a43348cfb14fa128d1f593b479a1eaf99bd/docker/curatedMetagenomics/curatedMetagenomicData_pipeline.sh#L58

**Comment by fbeghini** [comment]
The DB is not planned to be updated in the foreseeable future, however `$mdbn` can be set to `latest` in order to use the latest version (the value is fetched from the `mpa_latest` file) or
