### ISSUE TITLE
Create docker image with pipeline and scripts inside

### ISSUE THREAD

**Issue by seandavi** [waldronlab/curatedMetagenomicDataHighLoad#2]
- [X] Copy scripts from pipeline into container in dockerfile
- [ ] In pipeline, check for existence of database files (which could be present using volume mount)
- [ ] Download database files if not present
- [ ] Script to actually run pipeline (and capture log output)
- [ ] Script to push results and logs to cloud storage (this one will be implementation specific)

**Comment by lwaldron** [comment]
I will close this but keep it for reference, opening smaller / more discrete issues.
