### ISSUE TITLE
Change download URLs to environment variables

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicDataHighLoad#20]
For chocophlan and uniref. For example:

https://github.com/waldronlab/curatedMetagenomicDataHighLoad/blob/aacab68a9aebecef45fa741153e80bd16d63d7f4/docker/curatedMetagenomics/download_chocophlan.sh#L26

**Comment by lwaldron** [comment]
See how environment variables are instructed to be set on [this wiki](https://github.com/waldronlab/curatedMetagenomicDataHighLoad/wiki/Environment-variables-and-invocation).

These programs should:
1. error if either environment variable isn't set
2. use `gs_util` if the `gs_util` executable is available and variables are set to Google Bucket paths

- [ ] change [download_chocophlan.sh](https://github.com/waldronlab/curatedMetagenomicDataHighLoad/blob/master/docker/curatedMetagenomics/download_chocophlan.sh)
- [ ] change [download_uniref.sh](https://github.com/waldronlab/curatedMetagenomicDataHighLoad/blob/master/docker/curatedMetagenomics/download_uniref.sh)

**Comment by lwaldron** [comment]
@fbeghini are you planning to do this? Let me know if not, and I will do it.

**Comment by fbeghini** [comment]
Yes, I planned to do this in the weekend

----

Francesco Beghini

PhD Student


Lab. of Computational Metagenomics

Department of Cellular, Computational and Integrative Biology - CIBIO

University of Trento
Via Sommarive 9, 38123 Trento, Italy

Il Ven 15 Mag 2020, 23:32 Levi Waldron <notifications@github.com> ha
scritto:

**Comment by fbeghini** [comment]
Solved in https://github.com/waldronlab/curatedMetagenomicDataHighLoad/commit/461fe5fc8a8b89c119cfef17d969179c9e43ae0d
