### ISSUE TITLE
Separate humann from metaphlan

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedMetagenomicDataHighLoad#21]
Currently run in one line:

https://github.com/waldronlab/curatedMetagenomicDataHighLoad/blob/aacab68a9aebecef45fa741153e80bd16d63d7f4/docker/curatedMetagenomics/curatedMetagenomicData_pipeline.sh#L122

These should be run as two separate bash / python functions, with the metaphlan output directory as humann input directory. Use environment variables or run arguments for any database directories needed.

**Comment by fbeghini** [comment]
Resolved in 99d175ef170e123ccb2a53360667ee0e4f2f5daa
