### ISSUE TITLE
read-only file system error with singularity

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/curatedMetagenomicDataHighLoad#27]
running singularity exec curatedmetagenomics_latest.sif download_chocophlan.sh

Saving to: 'full_chocophlan.v296_201901.tar.gz'

full_chocophlan.v296_201901.t 100%[=================================================>]  15.29G  15.3MB/s    in 17m 16s 

2020-06-03 08:27:28 (15.1 MB/s) - 'full_chocophlan.v296_201901.tar.gz' saved [16423796221/16423796221]

g__Abditibacterium.s__Abditibacterium_utsteinense.centroids.v296_201901.ffn.gz
tar: g__Abditibacterium.s__Abditibacterium_utsteinense.centroids.v296_201901.ffn.gz: Cannot open: Read-only file system
g__Abiotrophia.s__Abiotrophia_defectiva.centroids.v296_201901.ffn.gz
tar: g__Abiotrophia.s__Abiotrophia_defectiva.centroids.v296_201901.ffn.gz: Cannot open: Read-only file system
g__Abiotrophia.s__Abiotrophia_sp_HMSC24B09.centroids.v296_201901.ffn.gz
tar: g__Abiotrophia.s__Abiotrophia_sp_HMSC24B09.centroids.v296_201901.ffn.gz: Cannot open: Read-only file system
g__Absiella.s__Absiella_dolichum.centroids.v296_201901.ffn.gz
tar: g__Absiella.s__Absiella_dolichum.centroids.v296_201901.ffn.gz: Cannot open: Read-only file system
g__Absiella.s__Absiella_sp_AM09_45.centroids.v296_201901.ffn.gz
t

**Comment by lwaldron** [comment]
I guess this can be included in #17, since I think filesystem directories are the only remaining Singularity issues. @vjcitn what environment variables did you set?
